#!/bin/bash

path=~/.config/myConfigs #Path to local repo

cd $path 

echo 'Введи коменратий к коммиту'
read comment 

git add . 
git commit -m "Обновляем конфиги $comment"
git push origin master


git switch neovim
git add nvim
git commit -m "Обновляем конфиги $comment"
git push origin neovim

git switch master
