#!/bin/bash

path=~/.config/my-configs #Path to local repo

cd $path 

echo 'Введи коменратий к коммиту'
read comment 

git add . 
git commit -m "Обновляем конфиги $comment"
git push origin master
git push disroot master
